name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      #run: mvn -B package --file pom.xml
      run: mvn clean install

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Listar arquivos gerados
      run: ls -l

    - name: Listar arquivos gerados
      run: ls -la target

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ldskmain/komorebi:latest

